"""D2

Revision ID: 7680868ecf19
Revises: e0d72b1b9a49
Create Date: 2023-01-26 23:51:52.505337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7680868ecf19'
down_revision = 'e0d72b1b9a49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_roles_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'roles_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_roles_id_fkey', 'user', 'role', ['roles_id'], ['id'])
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###
