"""DB CREATE

Revision ID: 8048066d16f0
Revises: 
Create Date: 2023-01-25 18:34:56.103138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8048066d16f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
            op.create_table('rules',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('permissions', sa.JSON(), nullable=True),
            sa.PrimaryKeyConstraint('id')
    )
            op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('username', sa.String(), nullable=False),
            sa.Column('password', sa.String(), nullable=False),
            sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
            sa.Column('roles_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['roles_id'], ['rules.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('rules')
    # ### end Alembic commands ###
