"""Added mmr tables

Revision ID: ce943040b59e
Revises: e717d5a81f18
Create Date: 2023-02-08 21:28:16.227389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce943040b59e'
down_revision = 'e717d5a81f18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mmr', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mmr')
    # ### end Alembic commands ###
