"""D1

Revision ID: e0d72b1b9a49
Revises: 64ffb7ec407a
Create Date: 2023-01-26 23:36:59.562565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d72b1b9a49'
down_revision = '64ffb7ec407a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
