"""Added mmr tables

Revision ID: e6ebf8f16431
Revises: ce943040b59e
Create Date: 2023-02-08 21:39:56.151406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ebf8f16431'
down_revision = 'ce943040b59e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
