"""Added mmr tables

Revision ID: e717d5a81f18
Revises: 7680868ecf19
Create Date: 2023-02-08 21:18:20.075305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e717d5a81f18'
down_revision = '7680868ecf19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
